Bugfix 56 interface
fga-eps-mds/2020.1-Minacademy-FrontEnd pull request #14
Opened 2020-10-02 03:43 UTC by EduardoPicolo

# Bugfix - Interface

## Descrição

Resolve diversos problemas de interface

## Issue Relacionada

#56 [fga-eps-mds/2020.1-Minacademy-Wiki/issues/56]

## Como isso foi testado?

- [ ] Testes unitários
- [x] Teste exploratório
- [ ] Não aplicável

## Imagens (se aplicável)

Alerta de erro
![image](https://user-images.githubusercontent.com/49292747/94885865-cfc64a00-0447-11eb-9efe-f5a21b7e219c.png)
Alerta de sucesso
![image](https://user-images.githubusercontent.com/49292747/94885873-d48afe00-0447-11eb-9b2c-ee4931fe5a39.png)

## Essa modificação exige atualização da documentação?

Não

## Tipo de alteração

- [ ] Nova feature
- [x] Correção de bugs
- [ ] Alteração de uma funcionalidade já existente
- [ ] Documentação

2020-10-02 11:49 UTC, GeovanaRamos requested changes
Pessoal, melhorou BASTANTE! Parabéns pelo capricho. Adorei a forma como mostram mensagens no site, além de uma melhoria muito grande no formulário cadastro. Tem apenas algumas coisinhas que faltaram e por isso vou pedir o ajuste. Cito aqui mesmo:
- A caixa de mensagens que aparece na direita as vezes fica em cima de botões importantes na nav. Mesmo sendo temporário, ficaria mais agradável se ele aparecesse um pouco mais abaixo verticalmente, de forma a não cobrir a nav.
- Quando me cadastro com o mesmo email, o erro é de erro no servidor, e deveria ser algo como "Este e-mail já está cadastrado". 
- Lembram o que falamos sobre tirar coisas do site que na verdade não existem? O checkbox de termo de uso, creio ser desnecessário.
- O campo de concordar que o tutorial é somente para o gênero femino, não possui mensagem de erro quando não marcado.
- A frase _Nós encorajamos mulheres a se apaixonarem por programação_ precisa de um ponto final.
- A frase bem vindo faltou o hífen e faltou ajustar para A ou O dependendo do gênero (lembrando que mentores podem ser homens). Esse acho que depende do outro bugfix. Então não vou exigir, apenas o **hífen**. Mas mantenham isso em mente.
- Olá <Usuário> deve ter uma vírgula após o Olá.
- **Os testes não estão passando.**

Acredito que sejam correções pontuais, então peço que façam o mais rápido possível para que façam o merge e as outras issues possam fazer o rebase. Além do que foi falado, revisem novamente o português em geral, posso ter passado batido em outras coisas. No geral, parabéns pelo capricho e a criatividade e em corrigir o que foi pedido.

2020-10-02 14:40 UTC, EduardoPicolo commented
>     * **Os testes não estão passando.**

Removemos os snapshots, mas o ci ainda espera os mesmos

2020-10-02 15:04 UTC, gabiMSilva commented
> > ```
> > * **Os testes não estão passando.**
> > ```
> 
> Removemos os snapshots, mas o ci ainda espera os mesmos
> ![image](https://user-images.githubusercontent.com/49292747/94936155-42651300-04a4-11eb-8824-1e03e7386f48.png)

O CI só roda os arquivos de teste, ele não diz o que deve ser feito.

Vcs já removeram as funções .toMatchSnapshot() dos testes?

2020-10-02 15:07 UTC, GeovanaRamos commented
O teste não passa nem localmente. Você rodou os testes antes de abrir o pr?
![image](https://user-images.githubusercontent.com/31005087/94938942-ddabb780-04a7-11eb-9cff-cafd6a4ec628.png)

2020-10-02 15:13 UTC, luucas-melo commented
> O teste não passa nem localmente. Você rodou os testes antes de abrir o pr?
> ![image](https://user-images.githubusercontent.com/31005087/94938942-ddabb780-04a7-11eb-9cff-cafd6a4ec628.png)

Eu tinha tirado, subi dps de dar amend no commit pq tinha subido com os testes, engraçado que rodei os testes e passaram todos, vou fazer as mudanças e subo dnv sem os snapshots

2020-10-02 17:08 UTC, GeovanaRamos commented
Vou só aguardar as outras correções para aprovar.

2020-10-02 18:24 UTC, luucas-melo commented
![image](https://user-images.githubusercontent.com/48891167/94956930-53714c80-04c3-11eb-9c9b-3659548d151c.png)

Fica muito estranho com ponto final, acho melhor deixar sem

2020-10-03 00:45 UTC, GeovanaRamos approved these changes

2020-10-03 00:46 UTC, gabiMSilva approved these changes

2020-10-03 00:46 UTC, merged