77 certificado
fga-eps-mds/2020.1-Minacademy-FrontEnd pull request #25
Opened 2020-10-23 19:52 UTC by estevaoreis25

# US08 - Fornecer certificado ao aprendiz concluir curso

## Descrição

Quando a aprendiz conclui todas asa atividades um modal é mostrado avisando que o certificado de aluno foi gerado e um link fica disponível para visualização. Além disso é fica disponível na dashboard um link para uma pagina onde contem todos os seus certificados

## Issue Relacionada

#[77](https://github.com/fga-eps-mds/2020.1-Minacademy-Wiki/issues/77)

## Como isso foi testado?

- [x] Testes unitários
- [x] Teste exploratório
- [ ] Não aplicável

## Imagens (se aplicável)

![image](https://user-images.githubusercontent.com/30116525/97047739-c6fcfb80-154f-11eb-8da7-00524ca53dae.png)

![image](https://user-images.githubusercontent.com/30116525/97047778-dbd98f00-154f-11eb-90c3-6932044f664b.png)

## Tipo de alteração

- [x] Nova feature
- [ ] Correção de bugs
- [ ] Alteração de uma funcionalidade já existente
- [ ] Documentação

2020-10-23 20:54 UTC, GeovanaRamos requested changes
Sugestão:
- Inverter os botões de cancelar e visualizar. Sites com boa usabilidade padronizam o lado dos botões de prosseguir/enviar e os de cancelar/voltar. Em nosso site os botões de prosseguir/enviar ficam a esquerda quando nao centralizados.

Problemas:
- Teste no front abaixo de 30% de cobertura de linhas
- O ideal é que o certificado abra em uma nova aba.
- O design do certificado deixou a desejar:
  * O tipo do certificado está em inglês (Learner)
  * O design no geral não está próximo dos exemplos que demos, apesar de ter todos os dados. É possivel encontrar templates na internet prontos, faltando apenas a estilização. Ex: https://support.edubrite.com/oltpublish/site/cms.do?view=html_certificate. Deixem com mais cara de certificado.

PS: A pagina que lista os certificados ficou muito boa

2020-10-23 21:00 UTC, gabiMSilva requested changes
- Falta o nome do curso (o curso é de Django e não tem nada sobre isso no certificado)
- Falta a hash de verificação

2020-10-23 21:02 UTC, GeovanaRamos commented
Extra: vi**s**ualizar é com S. Tenham mais cuidado com os textos que colocam no site. Tem muitos erros de português e alguns muito sérios. Lembre-se que o site carrega o nome de vcs como devs. Tenham mais cuidado.

2020-10-23 21:12 UTC, luucas-melo commented
> * Falta a hash de verificação

oq seria isso? Tem que colocar no certificado?

2020-10-23 21:18 UTC, GeovanaRamos commented
> > * Falta a hash de verificação
> 
> oq seria isso? Tem que colocar no certificado?
> 
> No backend eu tô gerando uma chave, mas ela é muito grande

Seria ela mesmo. Se não me engano, nos exemplos que mandei tem uma chave grande tbm. Se não der muito trabalho, dá pra gerar um qr code, ai fica mais interessante. Porém adicionar a chave é suficiente.

2020-10-23 21:18 UTC, gabiMSilva commented
> > * Falta a hash de verificação
> 
> oq seria isso? Tem que colocar no certificado?
> 
> No backend eu tô gerando uma chave, mas ela é muito grande

É ela mesmo. No exemplo que tem na issue tem a chave embaixo também

2020-10-23 22:46 UTC, luucas-melo commented
@GeovanaRamos @gabiMSilva não consigo testar os componentes pois eles tão usando hooks, única forma que achei foi com o WithRouter do 'react-router-dom', mas ele gera um snapshot

2020-10-24 01:06 UTC, gabiMSilva commented
Só uma correção. É "atividades **relativas**". Fora isso tudo certo pra mim

2020-10-24 01:10 UTC, gabiMSilva approved these changes

2020-10-24 12:53 UTC, GeovanaRamos approved these changes

2020-10-24 12:54 UTC, merged