Bugfix 98 curso
fga-eps-mds/2020.1-Minacademy-FrontEnd pull request #37
Opened 2020-11-18 19:34 UTC by luucas-melo

# BUGFIX - Curso

## Descrição

Corrige problemas no tutorial e na avaliação de mentoria
- melhoria na navegação
- adicionado ícone no dropdown
- adicionado percentual de acertos da avaliacao

## Issue Relacionada

#[98](https://github.com/fga-eps-mds/2020.1-Minacademy-Wiki/issues/98)
## Como isso foi testado?

- [ ] Testes unitários
- [x] Teste exploratório
- [ ] Não aplicável

## Imagens (se aplicável)

![gifMDS](https://user-images.githubusercontent.com/48891167/99578155-27e6ea80-29bb-11eb-8791-48531cd8fbcc.gif)

## Essa modificação exige atualização da documentação?

Não

## Tipo de alteração

- [ ] Nova feature
- [x] Correção de bugs
- [ ] Alteração de uma funcionalidade já existente
- [ ] Documentação

2020-11-18 22:46 UTC, gabiMSilva commented
Tem alguns critérios na issue que não foram marcados. Caso não tenham feito, expliquem o motivo disso aqui no PR. E caso tenham feito, marquem na issue por favor.

2020-11-18 23:27 UTC, luucas-melo commented
> Tem alguns critérios na issue que não foram marcados. Caso não tenham feito, expliquem o motivo disso aqui no PR. E caso tenham feito, marquem na issue por favor.

 Como explicado no daily de hoje:
1 - Não conseguimos reproduzir o bug que colocaram como critério da issue, a @GeovanaRamos disse que iria tentar reproduzir e nos falar o que era e nos informar, estamos no aguardo mas já abrimos o PR para que já possam corrigir e ver se tá com esse bug mesmo. Já debugamos o código e não conseguimos encontrar problema. 

2 - Como dissemos na daily, achamos que não há necessidade de colocar o dropdown de módulos no meio de uma atividade, já que possuímos essa navegação pela sidebar, assim como ocorre em outras plataformas de cursos, como no Coursera. Essa implementação ainda é inviável e provavelmente incluiria mais bugs.

2020-11-19 12:05 UTC, GeovanaRamos requested changes
1- Essa questão, que está apontada na issue de vocês, não está boa porque a pessoa tem que voltar ao tutorial. Coloquem o tal erro na questão, ou troquem.
![image](https://user-images.githubusercontent.com/31005087/99663757-d8013580-2a45-11eb-8966-5b8fa55760ee.png)

2 - O balanço de respostas ainda nao foi corrigido. <br>a:10<br>b:6<br>**c:23**<br>d:6

2020-11-19 12:12 UTC, GeovanaRamos commented
3 - Marquem reviwer e assignee no back

2020-11-19 12:35 UTC, gabiMSilva requested changes
![WhatsApp Image 2020-11-19 at 09 11 50](https://user-images.githubusercontent.com/36926637/99665304-36c7ae80-2a48-11eb-80fd-d8bf479c0868.jpeg)

Essa link para voltar para o texto não ficou bom. Por um momento nem encontrei onde estava.

- [ ] Trocar o título "Atividades" para o nome do módulo
- [ ] O link para o texto deve estar estilizado da mesma forma que as atividades ( "Conteúdo", "Atividade 1", "Atividade 2" ), todos um embaixo do outro.

2020-11-19 13:35 UTC, EduardoPicolo commented
> 
> Essa link para voltar para o texto não ficou bom. Por um momento nem encontrei onde estava.
> 
>     * [ ]  Trocar o título "Atividades" para o nome do módulo
> 
>     * [ ]  O link para o texto deve estar estilizado da mesma forma que as atividades ( "Conteúdo", "Atividade 1", "Atividade 2" ), todos um embaixo do outro.

Troquei o link, mas colocar o nome do modulo ficou muito estranho

![Captura de tela de 2020-11-19 10-28-27](https://user-images.githubusercontent.com/49292747/99672454-33392500-2a52-11eb-8436-31f93093637f.png)
![image](https://user-images.githubusercontent.com/49292747/99672469-37fdd900-2a52-11eb-840e-a6e1ee8de5db.png)

2020-11-19 14:02 UTC, gabiMSilva commented
> > Essa link para voltar para o texto não ficou bom. Por um momento nem encontrei onde estava.
> > ```
> > * [ ]  Trocar o título "Atividades" para o nome do módulo
> > 
> > * [ ]  O link para o texto deve estar estilizado da mesma forma que as atividades ( "Conteúdo", "Atividade 1", "Atividade 2" ), todos um embaixo do outro.
> > ```
> 
> Troquei o link, mas colocar o nome do modulo ficou muito estranho
> 
> ![Captura de tela de 2020-11-19 10-28-27](https://user-images.githubusercontent.com/49292747/99672454-33392500-2a52-11eb-8436-31f93093637f.png)
> ![image](https://user-images.githubusercontent.com/49292747/99672469-37fdd900-2a52-11eb-840e-a6e1ee8de5db.png)

Vocês já deram push nessas alterações? Não tá aparecendo aqui

2020-11-19 18:14 UTC, EduardoPicolo commented
Encontramos um bug ao logar com email não cadastrado, estamos arrumando.

2020-11-19 21:43 UTC, gabiMSilva commented
<img width="1792" alt="Captura de Tela 2020-11-19 às 18 34 49" src="https://user-images.githubusercontent.com/36926637/99727004-1aeaf980-2a96-11eb-838d-8ed765409c9c.png">

O título na side continua "Atividades"

2020-11-19 21:58 UTC, gabiMSilva commented
Quando o usuário acerta a última atividade do módulo e clica em "Continuar Tutorial", ele deve ir para o próximo módulo não voltar para o conteúdo do módulo que ele está, isso quebra o fluxo do usuário.

2020-11-19 22:25 UTC, luucas-melo commented
> Quando o usuário acerta a última atividade do módulo e clica em "Continuar Tutorial", ele deve ir para o próximo módulo não voltar para o conteúdo do módulo que ele está (confirmem se isso está acontecendo mesmo, quando rodo localmente meu tutorial tem um bugs).
> 
Não é um bug, já vou subir essa modificação.

2020-11-19 23:45 UTC, luucas-melo commented
Fiz como foi pedido, achei meio redundante, já que o nome do módulo atual aparece 3 vezes.
![image](https://user-images.githubusercontent.com/48891167/99737850-eed87400-2aa7-11eb-9801-6c580467a61b.png)

2020-11-20 12:21 UTC, gabiMSilva requested changes
<img width="1792" alt="Captura de Tela 2020-11-20 às 09 19 48" src="https://user-images.githubusercontent.com/36926637/99799547-a05fbf80-2b11-11eb-8ac5-b518692834dc.png">

Isso aconteceu quando fui confirmar meu e-mail após cadastro.

Quanto ao título, ficou ótimo assim. No conteúdo pode até ficar redundante, mas nas atividades, que não possuem nem dropdown nem título, é o único indicativo do nome do módulo. E o botão para o próximo módulo ficou certinho também. Só ver esse erro aí e tá tudo certo =D

2020-11-20 13:00 UTC, EduardoPicolo commented
> <img alt="Captura de Tela 2020-11-20 às 09 19 48" width="1792" src="https://user-images.githubusercontent.com/36926637/99799547-a05fbf80-2b11-11eb-8ac5-b518692834dc.png">
> 
> Isso aconteceu quando fui confirmar meu e-mail após cadastro.
> 
> Quanto ao título, ficou ótimo assim. No conteúdo pode até ficar redundante, mas nas atividades, que não possuem nem dropdown nem título, é o único indicativo do nome do módulo. E o botão para o próximo módulo ficou certinho também. Só ver esse erro aí e tá tudo certo =D

Comentei esse problema no PR https://github.com/fga-eps-mds/2020.1-Minacademy-FrontEnd/pull/38/#issuecomment-731107238 , há modificações no componente de confirmação de cadastro, mas o problema ainda persiste. Vou ajudar o @estevaoreis25 na correção, as modificações podem demorar.

2020-11-20 13:21 UTC, gabiMSilva commented
> > <img alt="Captura de Tela 2020-11-20 às 09 19 48" width="1792" src="https://user-images.githubusercontent.com/36926637/99799547-a05fbf80-2b11-11eb-8ac5-b518692834dc.png">
> > Isso aconteceu quando fui confirmar meu e-mail após cadastro.
> > Quanto ao título, ficou ótimo assim. No conteúdo pode até ficar redundante, mas nas atividades, que não possuem nem dropdown nem título, é o único indicativo do nome do módulo. E o botão para o próximo módulo ficou certinho também. Só ver esse erro aí e tá tudo certo =D
> 
> Comentei esse problema no PR #38 , há modificações no componente de confirmação de cadastro, mas o problema ainda persiste. Vou ajudar o @estevaoreis25 na correção, as modificações podem demorar.

Ah, ótimo. Então vou fechar esse PR e espero a correção no outro

2020-11-20 13:23 UTC, gabiMSilva approved these changes

2020-11-20 19:46 UTC, gabiMSilva approved these changes
A contagem após confirmação do cadastro ficou ótima, parabéns!

2020-11-20 19:49 UTC, merged