Bugfix 99 mentoria
fga-eps-mds/2020.1-Minacademy-FrontEnd pull request #39
Opened 2020-11-20 18:16 UTC by peHaick

# Bugfix 99 mentoria

## Descrição

Correção de defeitos e problemas relacionados os fluxos de mentor

## Issue Relacionada

#99

## Como isso foi testado?

- [x] Testes unitários
- [x] Teste exploratório
- [ ] Não aplicável

## Imagens (se aplicável)

[Adicionar prints de tela caso a funcionalidade tenha parte visual]

## Essa modificação exige atualização da documentação?

Não

## Tipo de alteração

- [ ] Nova feature
- [x] Correção de bugs
- [ ] Alteração de uma funcionalidade já existente
- [ ] Documentação

2020-11-20 20:35 UTC, GeovanaRamos requested changes
Eu encontrei apenas um erro porém grave. O que eu fiz:
- Cadastrei um mentor e NÃO validei ele
- Cadastrei um aprendiz e terminei o curso com ele, portanto se tornou mentor.
- Cadastrei um novo aprendiz e solicitei mentor ao cadastrar.

Erro: no terceiro passo, meu aprendiz deveria receber o aprendiz que virou mentor como mentor. Ele não recebeu ninguém. Segue o estado(resumido) dos usuários no meu banco pra ajudar na correção(resumido):
```
[{
  "_id": {
    "$oid": "5fb823956190b70023f0ec98"
  },
  "isValidated": false,
  "isAvailable": false,
  "learners": [],
  "attempts": 3,
  "noAssociations": [],
  "courseCertificates": [],
  "showMessageConfirm": false,
  "isRegistered": true,
  "userType": "Mentor",
  "name": "Mentor",
  "lastname": "M",
  "email": "m@email.com",
},{
  "_id": {
    "$oid": "5fb824676190b70023f0ec9a"
  },
  "noAssociations": [],
  "courseCertificates": [
    {
      "$oid": "5fb8258b6190b70023f0ecd6"
    }
  ],
  "showMessageConfirm": false,
  "isRegistered": true,
  "userType": "Mentor",
  "name": "Aprendiz",
  "lastname": "Um",
  "email": "a1@email.com",
  "attempts": 3,
  "isAvailable": true,
  "isValidated": true,
  "learners": []
},{
  "_id": {
    "$oid": "5fb8261d6190b70023f0ecd8"
  },
  "noAssociations": [],
  "courseCertificates": [],
  "showMessageConfirm": false,
  "isRegistered": true,
  "userType": "Learner",
  "name": "Aprendiz",
  "lastname": "Dois",
  "email": "a2@email.com",
}]
```

2020-11-20 20:39 UTC, GeovanaRamos commented
Complementando a mensagem acima, acredito que a vinculação logo após o cadastro não esteja funcionando. Ou seja, se o aprendiz se cadastrar com a opção de se vincular ao mentor, ele não vai ser atribuido de cara. Se não for isso, é espeficifico da situação acima (um mentor que era aprendiz).

2020-11-20 20:39 UTC, peHaick commented
> Eu encontrei apenas um erro porém grave. O que eu fiz:
> 
> * Cadastrei um mentor e NÃO validei ele
> * Cadastrei um aprendiz e terminei o curso com ele, portanto se tornou mentor.
> * Cadastrei um novo aprendiz e solicitei mentor ao cadastrar.
> 
> Erro: no terceiro passo, meu aprendiz deveria receber o aprendiz que virou mentor como mentor. Ele não recebeu ninguém. Segue o estado(resumido) dos usuários no meu banco pra ajudar na correção:
> 
> ```
> [{
>   "_id": {
>     "$oid": "5fb823956190b70023f0ec98"
>   },
>   "isValidated": false,
>   "isAvailable": false,
>   "learners": [],
>   "attempts": 3,
>   "noAssociations": [],
>   "courseCertificates": [],
>   "showMessageConfirm": false,
>   "isRegistered": true,
>   "userType": "Mentor",
>   "name": "Mentor",
>   "lastname": "M",
>   "email": "m@email.com",
> },{
>   "_id": {
>     "$oid": "5fb824676190b70023f0ec9a"
>   },
>   "noAssociations": [],
>   "courseCertificates": [
>     {
>       "$oid": "5fb8258b6190b70023f0ecd6"
>     }
>   ],
>   "showMessageConfirm": false,
>   "isRegistered": true,
>   "userType": "Mentor",
>   "name": "Aprendiz",
>   "lastname": "Um",
>   "email": "a1@email.com",
>   "attempts": 3,
>   "isAvailable": true,
>   "isValidated": true,
>   "learners": []
> },{
>   "_id": {
>     "$oid": "5fb8261d6190b70023f0ecd8"
>   },
>   "noAssociations": [],
>   "courseCertificates": [],
>   "showMessageConfirm": false,
>   "isRegistered": true,
>   "userType": "Learner",
>   "name": "Aprendiz",
>   "lastname": "Dois",
>   "email": "a2@email.com",
> }]
> ```

Isso acontece pq o vinculo é feito na página de bem-vindo, que não está sendo acessada por causa da confirmação de cadastro. O rodrigo corrigiu esse problema, mas subiu ele na branch do estevão

2020-11-21 00:01 UTC, GeovanaRamos approved these changes

2020-11-21 00:04 UTC, merged